identifier: REMOVE_ME

# Use by init_keys.sh
ssl_params:
  country: "MY"
  state: "Penang"
  locality: "Batu Feringgi"
  organization: "Your Company"
  organizational_unit: "Your Department"
  # Must be valid domain name. It critical for validation process
  common_name: "www.example.com"
  email_address: "email@example.com"

server:
  # Port for signet server, Dont cghange if you dont know
  port: 55619
  max_connection: 60
  server_p12: "keys/signetserver.jks"
  # Use pin from finilize_keys.sh
  server_p12_pin: "your_pin_here"
  server_alias: "signetserver"
  trusted_cert_store: "keys/signetserver_trustedca.jks"
  # Use pin from finilize_keys.sh
  trusted_cert_store_pin: "your_pin_here"
  db:
    # Mostly mysql please dont chnage if you dont know
    type: "mysql"
    username: "signet"
    # Choose better password
    password: "change_me"
    # Mostly mysql please dont chnage if you dont know
    host: "mysql:3306"
    driver: "com.mysql.cj.jdbc.Driver"
    name: "signet"
    max_total_connection: 60
    max_idle_connection: 30
    idle_connection_timeout: 60000
    connection_max_wait_timeout: 20000
